# Generated by Django 3.0 on 2020-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191219_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='motor_diameter',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
