# Generated by Django 3.0 on 2020-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_design_motor_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='diameter',
            field=models.DecimalField(decimal_places=3, default=55, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='fin_description',
            field=models.CharField(default='Fins', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='length',
            field=models.DecimalField(decimal_places=3, default=650, max_digits=6),
            preserve_default=False,
        ),
    ]
