# Generated by Django 3.0 on 2020-01-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200109_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('notes', models.CharField(max_length=1000)),
                ('attendance', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='design',
            name='diameter',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='design',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
                ('temperature', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('weather_notes', models.CharField(max_length=500)),
                ('payload_description', models.CharField(max_length=20)),
                ('booster_description', models.CharField(max_length=20)),
                ('motor_description', models.CharField(max_length=20)),
                ('motor_delay', models.IntegerField()),
                ('parachute_size', models.IntegerField()),
                ('parachute_description', models.CharField(max_length=20)),
                ('cg_separation_from_cp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('egg_mass', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wadding_mass', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ballast_mass', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motor_mass', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_mass', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altitude', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('modifications_made', models.CharField(max_length=256)),
                ('damages', models.CharField(max_length=256)),
                ('flight_characteristics', models.CharField(max_length=500)),
                ('considerations_for_next_flight', models.CharField(max_length=256)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='home.Launch')),
            ],
        ),
    ]
