# Generated by Django 3.0.2 on 2020-01-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200123_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='motor_description',
            new_name='motor_name',
        ),
    ]
