# Generated by Django 3.0.2 on 2020-01-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200124_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='payload_description',
            new_name='rocket_description',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='booster_description',
        ),
        migrations.AddField(
            model_name='design',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='home.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='home.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launch',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='home.Team'),
            preserve_default=False,
        ),
    ]
