# Generated by Django 3.0.2 on 2020-01-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200126_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cg_separation_from_cp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='motor_mass',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wadding_mass',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wind_speed',
            field=models.IntegerField(null=True),
        ),
    ]
