# Generated by Django 3.0.2 on 2020-01-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200126_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
