# Generated by Django 3.0.2 on 2020-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_flight_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='designFile',
            field=models.URLField(default='x.jpg', max_length=250),
        ),
    ]
