# Generated by Django 3.0.2 on 2020-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200203_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='designFile',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
