# Generated by Django 3.0.2 on 2020-02-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200203_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='designFile',
        ),
        migrations.AddField(
            model_name='design',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
