# Generated by Django 3.0.2 on 2020-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200212_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='upload',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
