# Generated by Django 3.0.2 on 2020-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200227_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='ballast_mass',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cg_separation_from_cp',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='egg_mass',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='motor_mass',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='total_mass',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wadding_mass',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
