# Generated by Django 3.0.2 on 2020-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200305_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
